packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  "@firebase/util": false
  "@nestjs/core": true
  "@parcel/watcher": true
  "@prisma/engines": true
  "@swc/core": true
  esbuild: true
  msw: false
  prisma: true
  protobufjs: false
  sharp: true
  unrs-resolver: true
