import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { prisma } from "@elorae/db";
import { generateDocNumber } from "./docNumber";

/**
 * `DocNumberConfig` holds ONE shared row per doc type on the :3308 bed, used by real dev data.
 * RECEIPT is generated by no other spec (vitest runs files serially), and the row is snapshotted
 * before each test and restored after it — or deleted, if this spec created it. A `beforeEach`
 * that dies before snapshotting leaves `snapshot` null, and teardown then touches nothing: a
 * default of "did not exist" would delete the real counter.
 */
type Snapshot =
  | { existed: false }
  | {
      existed: true;
      row: { prefix: string; resetPeriod: string; padding: number; lastNumber: number; year: number; month: number };
    };

let snapshot: Snapshot | null = null;

beforeEach(async () => {
  snapshot = null;
  const row = await prisma.docNumberConfig.findUnique({ where: { docType: "RECEIPT" } });
  snapshot = row
    ? {
        existed: true,
        row: {
          prefix: row.prefix,
          resetPeriod: row.resetPeriod,
          padding: row.padding,
          lastNumber: row.lastNumber,
          year: row.year,
          month: row.month,
        },
      }
    : { existed: false };
});

afterEach(async () => {
  if (!snapshot) return;
  if (snapshot.existed) {
    await prisma.docNumberConfig.update({ where: { docType: "RECEIPT" }, data: snapshot.row });
  } else {
    await prisma.docNumberConfig.deleteMany({ where: { docType: "RECEIPT" } });
  }
});

async function seedCounter(resetPeriod: string, year: number, lastNumber: number): Promise<void> {
  const data = { prefix: "RCPT/", resetPeriod, padding: 4, lastNumber, year, month: 12 };
  await prisma.docNumberConfig.upsert({
    where: { docType: "RECEIPT" },
    create: { docType: "RECEIPT", ...data },
    update: data,
  });
}

describe("generateDocNumber reset periods", () => {
  const currentYear = new Date().getFullYear();

  it("keeps counting across a year boundary when the reset period is NEVER", async () => {
    await seedCounter("NEVER", currentYear - 1, 41);

    expect(await generateDocNumber("RECEIPT")).toBe(`RCPT/${currentYear}/0042`);
    expect(await generateDocNumber("RECEIPT")).toBe(`RCPT/${currentYear}/0043`);
  });

  it("still restarts at 1 across a year boundary when the reset period is YEARLY", async () => {
    await seedCounter("YEARLY", currentYear - 1, 41);

    expect(await generateDocNumber("RECEIPT")).toBe(`RCPT/${currentYear}/0001`);
  });
});
