export type SalesOrderLine = {
  item_id: number;
  item_code: string;
  item_group_id: number;
  item_name?: string;
  qty: string | number;
  qty_in_base?: string | number | null;
  is_canceled_item?: boolean | null;
  salesorder_detail_id: number;
  sell_price?: string | number | null;
  price?: string | number | null;
  disc_amount?: string | number | null;
  tax_amount?: string | number | null;
  amount?: string | number | null;
  disc_marketplace?: string | number | null;
  discount_marketplace?: string | number | null;
  weight_in_gram?: string | number | null;
};

export type SalesOrderPayload = {
  action?: string;
  salesorder_id: number;
  salesorder_no?: string;
  channel_status?: string | null;
  internal_status?: string | null;
  wms_status?: string | null;
  is_canceled?: boolean | null;
  is_paid?: boolean | null;
  marked_as_complete?: boolean | null;
  is_shipped?: boolean | null;
  source?: number | null;
  source_name?: string | null;
  customer_name?: string | null;
  customer_phone?: string | null;
  customer_email?: string | null;
  shipping_full_name?: string | null;
  shipping_address?: string | null;
  shipping_area?: string | null;
  shipping_city?: string | null;
  shipping_province?: string | null;
  shipping_post_code?: string | null;
  shipping_country?: string | null;
  shipping_phone?: string | null;
  shipping_subdistrict?: string | null;
  sub_total?: string | number | null;
  total_disc?: string | number | null;
  total_tax?: string | number | null;
  grand_total?: string | number | null;
  shipping_cost?: string | number | null;
  insurance_cost?: string | number | null;
  add_fee?: string | number | null;
  add_disc?: string | number | null;
  service_fee?: string | number | null;
  escrow_amount?: string | number | null;
  voucher_amount?: string | number | null;
  cod_fee?: string | number | null;
  order_processing_fee?: string | number | null;
  shipping_tax?: string | number | null;
  total_amount_mp?: string | number | null;
  payment_method?: string | null;
  payment_date?: string | null;
  transaction_date?: string | null;
  created_date?: string | null;
  completed_date?: string | null;
  internal_cancel_date?: string | null;
  last_modified?: string | null;
  tracking_number?: string | null;
  courier?: string | null;
  items?: SalesOrderLine[];
};
