export const POSTING_ROLES = [
  "INVENTORY",
  "INVENTORY_FG",
  "AP",
  "AR",
  "SALES_REVENUE",
  "COGS",
  "BANK",
  "MARKETPLACE_FEE",
  "MARKETPLACE_FEE_ADMIN",
  "MARKETPLACE_FEE_SERVICE",
  "MARKETPLACE_FEE_COMMISSION",
  "MARKETPLACE_FEE_PROCESSING",
  "MARKETPLACE_FEE_OTHER",
  "INVENTORY_VARIANCE",
  "TAX",
] as const;

export type PostingRole = (typeof POSTING_ROLES)[number];
