ALTER TABLE `FieldReturn` ADD COLUMN IF NOT EXISTS `offsetStatus` ENUM('AVAILABLE', 'APPLIED') NOT NULL DEFAULT 'AVAILABLE';
ALTER TABLE `FieldReturn` ADD COLUMN IF NOT EXISTS `offsetPaymentId` VARCHAR(191) NULL;
ALTER TABLE `FieldReturn` ADD UNIQUE INDEX IF NOT EXISTS `FieldReturn_offsetPaymentId_key` (`offsetPaymentId`);
ALTER TABLE `Payment` MODIFY COLUMN `method` ENUM('CASH', 'TRANSFER', 'RETUR_OFFSET') NOT NULL;
ALTER TABLE `CollectionSubmission` MODIFY COLUMN `method` ENUM('CASH', 'TRANSFER', 'RETUR_OFFSET') NOT NULL;
