ALTER TABLE `Store` ADD COLUMN IF NOT EXISTS `npwp` VARCHAR(32) NULL;

ALTER TABLE `TaxInvoice` ADD COLUMN IF NOT EXISTS `buyerNpwp` VARCHAR(32) NULL;
ALTER TABLE `TaxInvoice` ADD COLUMN IF NOT EXISTS `taxableAmount` DECIMAL(15, 2) NULL;
ALTER TABLE `TaxInvoice` ADD COLUMN IF NOT EXISTS `ppnAmount` DECIMAL(15, 2) NULL;

ALTER TABLE `TaxInvoice`
  MODIFY COLUMN `status` ENUM('PENDING', 'CREATED', 'SENT_TO_STORE', 'NOT_REQUIRED')
  NOT NULL DEFAULT 'PENDING';
