-- AlterTable
ALTER TABLE `POStatusHistory` MODIFY `status` ENUM('DRAFT', 'SUBMITTED', 'PARTIAL', 'CLOSED', 'OVER', 'CANCELLED') NOT NULL;

-- AlterTable
ALTER TABLE `PurchaseOrder` ADD COLUMN `paidAt` DATETIME(3) NULL,
    ADD COLUMN `paymentDueDate` DATETIME(3) NULL,
    MODIFY `status` ENUM('DRAFT', 'SUBMITTED', 'PARTIAL', 'CLOSED', 'OVER', 'CANCELLED') NOT NULL DEFAULT 'DRAFT';
